<?php

namespace Database\Seeders;

use App\Enums\ActivityCategory;
use App\Models\ActivityType;
use Illuminate\Database\Seeder;

class ActivityTypeSeeder extends Seeder
{
    /**
     * Seed activity types for IOMeH health tracking platform.
     * 
     * Base Points Guide:
     * - Low Intensity (10-20 pts): Light activities, easy habits
     * - Moderate Intensity (25-35 pts): Regular daily activities
     * - High Intensity (40-50 pts): Vigorous activities, major commitments
     * - Very High Intensity (55-60 pts): Extreme effort, exceptional activities
     * 
     * Daily Target: ~90-100 points suggested
     */
    public function run(): void
    {
        $activities = [
            // ========================================
            // 💪 WORKOUT ACTIVITIES (30 total)
            // ========================================
            
            // VERY HIGH INTENSITY (55-60 points)
            [
                'name' => 'Fast Running',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 60,
                'icon' => '🏃‍♂️',
                'display_order' => 1,
                'description' => 'Running at 12+ km/h (7.5+ mph) for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Jump Rope Fast',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 55,
                'icon' => '🪢',
                'display_order' => 2,
                'description' => 'Fast continuous jump rope for 20+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'HIIT Training',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 55,
                'icon' => '⚡',
                'display_order' => 3,
                'description' => 'High-intensity interval training with burpees and sprints',
                'is_active' => true,
            ],
            [
                'name' => 'Fast Stair Climbing',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 55,
                'icon' => '🪜',
                'display_order' => 4,
                'description' => 'Climbing stairs quickly for 20+ minutes',
                'is_active' => true,
            ],

            // HIGH INTENSITY (40-50 points)
            [
                'name' => 'Jogging',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 45,
                'icon' => '🏃',
                'display_order' => 5,
                'description' => 'Moderate jogging at 8-11 km/h (5-7 mph) for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Swimming',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 45,
                'icon' => '🏊',
                'display_order' => 6,
                'description' => 'Swimming laps for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Cycling Fast',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 45,
                'icon' => '🚴‍♂️',
                'display_order' => 7,
                'description' => 'Fast cycling at 25+ km/h (16+ mph) for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Soccer',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 40,
                'icon' => '⚽',
                'display_order' => 8,
                'description' => 'Playing soccer or football for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Boxing',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 40,
                'icon' => '🥊',
                'display_order' => 9,
                'description' => 'Boxing or martial arts training for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Aerobics',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 40,
                'icon' => '💃',
                'display_order' => 10,
                'description' => 'High-impact aerobics workout for 30+ minutes',
                'is_active' => true,
            ],

            // MODERATE TO HIGH (30-40 points)
            [
                'name' => 'Weight Training',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 35,
                'icon' => '🏋️',
                'display_order' => 11,
                'description' => 'Strength training with weights for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Basketball',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 35,
                'icon' => '🏀',
                'display_order' => 12,
                'description' => 'Playing basketball for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Tennis',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 35,
                'icon' => '🎾',
                'display_order' => 13,
                'description' => 'Playing tennis for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Rowing',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 35,
                'icon' => '🚣',
                'display_order' => 14,
                'description' => 'Rowing machine or water rowing for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Hiking',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 30,
                'icon' => '🥾',
                'display_order' => 15,
                'description' => 'Hiking on trails for 45+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Cycling',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 30,
                'icon' => '🚴',
                'display_order' => 16,
                'description' => 'Moderate cycling at 16-24 km/h (10-15 mph) for 30+ minutes',
                'is_active' => true,
            ],

            // MODERATE (20-30 points)
            [
                'name' => 'Swimming Easy',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 25,
                'icon' => '🏊‍♀️',
                'display_order' => 17,
                'description' => 'Easy swimming or water exercise for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Badminton',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 25,
                'icon' => '🏸',
                'display_order' => 18,
                'description' => 'Playing badminton or volleyball for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Elliptical Machine',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 25,
                'icon' => '🚶‍♀️',
                'display_order' => 19,
                'description' => 'Elliptical trainer for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Brisk Walking',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 25,
                'icon' => '🚶‍♂️',
                'display_order' => 20,
                'description' => 'Fast walking at 6+ km/h (4+ mph) for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Circuit Training',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 25,
                'icon' => '💪',
                'display_order' => 21,
                'description' => 'Mixed circuit exercises for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Power Yoga',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 20,
                'icon' => '🧘',
                'display_order' => 22,
                'description' => 'Dynamic yoga practice for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Bodyweight Exercise',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 20,
                'icon' => '🤸‍♂️',
                'display_order' => 23,
                'description' => 'Push-ups, sit-ups, squats for 20+ minutes',
                'is_active' => true,
            ],

            // LIGHT TO MODERATE (10-20 points)
            [
                'name' => 'Walking',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 20,
                'icon' => '🚶',
                'display_order' => 24,
                'description' => 'Regular walking for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Pilates',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 15,
                'icon' => '🤸',
                'display_order' => 25,
                'description' => 'Pilates core exercises for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Gentle Yoga',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 15,
                'icon' => '🧘‍♀️',
                'display_order' => 26,
                'description' => 'Relaxing yoga practice for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Stretching',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 10,
                'icon' => '🤸‍♀️',
                'display_order' => 27,
                'description' => 'Full body stretching for 15+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Light Walk',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 15,
                'icon' => '🚶‍♀️',
                'display_order' => 28,
                'description' => 'Casual walking for 20+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Stair Climbing',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 30,
                'icon' => '🪜',
                'display_order' => 29,
                'description' => 'Regular stair climbing for 15+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Active House Chores',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 20,
                'icon' => '🏠',
                'display_order' => 30,
                'description' => 'Vigorous cleaning or gardening for 45+ minutes',
                'is_active' => true,
            ],
            
            // ========================================
            // 🥗 NUTRITION ACTIVITIES (15 total)
            // ========================================
            [
                'name' => 'Healthy Breakfast',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 20,
                'icon' => '🍳',
                'display_order' => 31,
                'description' => 'Nutritious breakfast with protein and whole grains',
                'is_active' => true,
            ],
            [
                'name' => 'Healthy Lunch',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 20,
                'icon' => '🥗',
                'display_order' => 32,
                'description' => 'Balanced lunch with vegetables and protein',
                'is_active' => true,
            ],
            [
                'name' => 'Healthy Dinner',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 20,
                'icon' => '🍽️',
                'display_order' => 33,
                'description' => 'Well-balanced dinner with quality nutrients',
                'is_active' => true,
            ],
            [
                'name' => 'Healthy Snacks',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 15,
                'icon' => '🥜',
                'display_order' => 34,
                'description' => 'Choosing nuts, fruits, or vegetables for snacks',
                'is_active' => true,
            ],
            [
                'name' => '5+ Servings Vegetables',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 25,
                'icon' => '🥦',
                'display_order' => 35,
                'description' => 'Eating 5 or more vegetable servings today',
                'is_active' => true,
            ],
            [
                'name' => '2+ Servings Fruit',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 15,
                'icon' => '🍎',
                'display_order' => 36,
                'description' => 'Eating 2 or more fruit servings today',
                'is_active' => true,
            ],
            [
                'name' => 'Adequate Protein',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 20,
                'icon' => '🥩',
                'display_order' => 37,
                'description' => 'Meeting daily protein needs with lean sources',
                'is_active' => true,
            ],
            [
                'name' => 'Drink 8+ Glasses Water',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 15,
                'icon' => '💧',
                'display_order' => 38,
                'description' => 'Drinking 8+ glasses (2+ liters) of water today',
                'is_active' => true,
            ],
            [
                'name' => 'Drink 12+ Glasses Water',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 25,
                'icon' => '💧💧',
                'display_order' => 39,
                'description' => 'Excellent hydration with 12+ glasses today',
                'is_active' => true,
            ],
            [
                'name' => 'No Processed Foods',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 25,
                'icon' => '🚫',
                'display_order' => 40,
                'description' => 'Avoiding all processed foods for the entire day',
                'is_active' => true,
            ],
            [
                'name' => 'Meal Prep',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 30,
                'icon' => '🥘',
                'display_order' => 41,
                'description' => 'Preparing healthy meals in advance',
                'is_active' => true,
            ],
            [
                'name' => 'Take Vitamins',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 10,
                'icon' => '💊',
                'display_order' => 42,
                'description' => 'Taking daily vitamins or supplements',
                'is_active' => true,
            ],
            [
                'name' => 'Whole Grains',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 15,
                'icon' => '🌾',
                'display_order' => 43,
                'description' => 'Eating whole grain products (brown rice, oats)',
                'is_active' => true,
            ],
            [
                'name' => 'Mindful Eating',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 15,
                'icon' => '🧘‍♂️',
                'display_order' => 44,
                'description' => 'Eating slowly without distractions',
                'is_active' => true,
            ],
            [
                'name' => 'Cook at Home',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 20,
                'icon' => '👨‍🍳',
                'display_order' => 45,
                'description' => 'Preparing meals at home instead of takeout',
                'is_active' => true,
            ],
            
            // ========================================
            // 🌟 WELLNESS ACTIVITIES (15 total)
            // ========================================
            [
                'name' => 'Sleep 7-9 Hours',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 30,
                'icon' => '😴',
                'display_order' => 46,
                'description' => 'Getting quality sleep for 7-9 hours',
                'is_active' => true,
            ],
            [
                'name' => 'Wake Up Early',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 15,
                'icon' => '🌅',
                'display_order' => 47,
                'description' => 'Waking up before 7 AM',
                'is_active' => true,
            ],
            [
                'name' => 'No Screens Before Bed',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 15,
                'icon' => '📵',
                'display_order' => 48,
                'description' => 'Avoiding screens 1 hour before bedtime',
                'is_active' => true,
            ],
            [
                'name' => 'Sunlight Exposure',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 15,
                'icon' => '☀️',
                'display_order' => 49,
                'description' => 'Getting 15-30 minutes of natural sunlight',
                'is_active' => true,
            ],
            [
                'name' => 'Time in Nature',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 20,
                'icon' => '🌳',
                'display_order' => 50,
                'description' => 'Spending 30+ minutes outdoors in nature',
                'is_active' => true,
            ],
            [
                'name' => 'Cold Shower',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 20,
                'icon' => '🚿',
                'display_order' => 51,
                'description' => 'Taking a cold shower for recovery',
                'is_active' => true,
            ],
            [
                'name' => 'Sauna',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 15,
                'icon' => '🧖‍♂️',
                'display_order' => 52,
                'description' => 'Using sauna for 15+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Quality Time with Family',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 20,
                'icon' => '👥',
                'display_order' => 53,
                'description' => 'Spending meaningful time with family or friends',
                'is_active' => true,
            ],
            [
                'name' => 'Self-Massage',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 15,
                'icon' => '💆',
                'display_order' => 54,
                'description' => 'Massage or foam rolling for recovery',
                'is_active' => true,
            ],
            [
                'name' => 'Good Posture',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 10,
                'icon' => '🧍‍♂️',
                'display_order' => 55,
                'description' => 'Maintaining good posture throughout the day',
                'is_active' => true,
            ],
            [
                'name' => 'Regular Bedtime',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 15,
                'icon' => '🕘',
                'display_order' => 56,
                'description' => 'Following consistent bedtime routine',
                'is_active' => true,
            ],
            [
                'name' => 'Active Recovery',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 15,
                'icon' => '🛋️',
                'display_order' => 57,
                'description' => 'Light movement or stretching on rest days',
                'is_active' => true,
            ],
            [
                'name' => 'Take Breaks',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 10,
                'icon' => '⏸️',
                'display_order' => 58,
                'description' => 'Taking regular breaks from work or screens',
                'is_active' => true,
            ],
            [
                'name' => 'Deep Breathing',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 10,
                'icon' => '💨',
                'display_order' => 59,
                'description' => 'Practicing deep breathing for 5+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Hygiene Routine',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 10,
                'icon' => '🧼',
                'display_order' => 60,
                'description' => 'Complete daily hygiene and self-care routine',
                'is_active' => true,
            ],
            
            // ========================================
            // 🧘 MINDFULNESS ACTIVITIES (15 total)
            // ========================================
            [
                'name' => 'Pray 5 Daily Prayers',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 40,
                'icon' => '🕌',
                'display_order' => 61,
                'description' => 'Completing all five daily prayers on time',
                'is_active' => true,
            ],
            [
                'name' => 'Read Quran',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 30,
                'icon' => '📖',
                'display_order' => 62,
                'description' => 'Reading Quran for 15+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Make Dua',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 15,
                'icon' => '🤲',
                'display_order' => 63,
                'description' => 'Making sincere supplication',
                'is_active' => true,
            ],
            [
                'name' => 'Remember Allah (Dhikr)',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 20,
                'icon' => '📿',
                'display_order' => 64,
                'description' => 'Dhikr and remembrance of Allah',
                'is_active' => true,
            ],
            [
                'name' => 'Meditation',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 25,
                'icon' => '🧘‍♀️',
                'display_order' => 65,
                'description' => 'Mindfulness meditation for 10+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Journaling',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 20,
                'icon' => '📝',
                'display_order' => 66,
                'description' => 'Daily journaling or gratitude practice',
                'is_active' => true,
            ],
            [
                'name' => 'Read Book',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 20,
                'icon' => '📚',
                'display_order' => 67,
                'description' => 'Reading for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Learn Islamic Knowledge',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 25,
                'icon' => '🎓',
                'display_order' => 68,
                'description' => 'Studying Islamic knowledge or attending lessons',
                'is_active' => true,
            ],
            [
                'name' => 'Digital Detox',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 25,
                'icon' => '📵',
                'display_order' => 69,
                'description' => 'Avoiding social media for the entire day',
                'is_active' => true,
            ],
            [
                'name' => 'Learn New Skill',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 20,
                'icon' => '🎯',
                'display_order' => 70,
                'description' => 'Learning or practicing a new skill for 30+ minutes',
                'is_active' => true,
            ],
            [
                'name' => 'Help Others',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 25,
                'icon' => '🤝',
                'display_order' => 71,
                'description' => 'Helping others or volunteering',
                'is_active' => true,
            ],
            [
                'name' => 'Set Goals',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 15,
                'icon' => '🎯',
                'display_order' => 72,
                'description' => 'Setting and reviewing personal goals',
                'is_active' => true,
            ],
            [
                'name' => 'Practice Gratitude',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 15,
                'icon' => '❤️',
                'display_order' => 73,
                'description' => 'Reflecting on things to be grateful for',
                'is_active' => true,
            ],
            [
                'name' => 'Active Listening',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 15,
                'icon' => '👂',
                'display_order' => 74,
                'description' => 'Practicing active listening in conversations',
                'is_active' => true,
            ],
            [
                'name' => 'Self-Reflection',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 15,
                'icon' => '🤔',
                'display_order' => 75,
                'description' => 'Taking time for self-reflection and assessment',
                'is_active' => true,
            ],
        ];

        foreach ($activities as $activity) {
            ActivityType::firstOrCreate(
                ['name' => $activity['name']],
                $activity
            );
        }

        $this->command->info('✓ Successfully seeded 75 activity types');
        $this->command->info('');
        $this->command->info('  📊 Category Breakdown:');
        $this->command->info('     💪 Workout: 30 activities (10-60 points)');
        $this->command->info('     🥗 Nutrition: 15 activities (10-30 points)');
        $this->command->info('     🌟 Wellness: 15 activities (10-30 points)');
        $this->command->info('     🧘 Mindfulness: 15 activities (15-40 points)');
        $this->command->info('');
        $this->command->info('  📈 Suggested Daily Target: 90-100 points');
        $this->command->info('     • Workout: 30-45 pts (1-2 activities)');
        $this->command->info('     • Nutrition: 25-35 pts (meals + hydration)');
        $this->command->info('     • Wellness: 20-30 pts (sleep + recovery)');
        $this->command->info('     • Mindfulness: 15-25 pts (1-2 practices)');
    }
}
