<?php

namespace Database\Seeders;

use App\Enums\ActivityCategory;
use App\Models\ActivityType;
use Illuminate\Database\Seeder;

class ActivityTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * Points are based on MET (Metabolic Equivalent of Task) values and health impact.
     * Formula: Points = MET value × 5 (rounded to nearest 5 for simplicity)
     */
    public function run(): void
    {
        $activityTypes = [
            // ===== WORKOUT ACTIVITIES =====
            // High Intensity (MET 8.0+)
            [
                'name' => 'Running (Fast)',
                'slug' => 'running-fast',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 50,
                'met_value' => 11.0,
                'icon' => '🏃‍♂️',
                'display_order' => 1,
                'description' => 'Running at 6+ mph (10 min/mile or faster)',
                'is_active' => true,
            ],
            [
                'name' => 'HIIT Training',
                'slug' => 'hiit-training',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 50,
                'met_value' => 10.0,
                'icon' => '⚡',
                'display_order' => 2,
                'description' => 'High-Intensity Interval Training',
                'is_active' => true,
            ],
            [
                'name' => 'CrossFit / Circuit Training',
                'slug' => 'crossfit',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 45,
                'met_value' => 9.0,
                'icon' => '🏋️‍♂️',
                'display_order' => 3,
                'description' => 'High-intensity functional fitness',
                'is_active' => true,
            ],
            [
                'name' => 'Swimming (Vigorous)',
                'slug' => 'swimming-vigorous',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 45,
                'met_value' => 9.0,
                'icon' => '🏊',
                'display_order' => 4,
                'description' => 'Fast-paced swimming laps',
                'is_active' => true,
            ],
            [
                'name' => 'Cycling (Fast)',
                'slug' => 'cycling-fast',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 40,
                'met_value' => 8.0,
                'icon' => '🚴‍♂️',
                'display_order' => 5,
                'description' => 'Cycling at 14-16 mph',
                'is_active' => true,
            ],
            [
                'name' => 'Jump Rope',
                'slug' => 'jump-rope',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 40,
                'met_value' => 8.0,
                'icon' => '🪢',
                'display_order' => 6,
                'description' => 'Continuous jump rope exercise',
                'is_active' => true,
            ],
            
            // Moderate Intensity (MET 4.0-7.9)
            [
                'name' => 'Running (Moderate)',
                'slug' => 'running-moderate',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 35,
                'met_value' => 7.0,
                'icon' => '🏃',
                'display_order' => 7,
                'description' => 'Running at 5 mph (12 min/mile)',
                'is_active' => true,
            ],
            [
                'name' => 'Gym / Weight Training',
                'slug' => 'gym-weights',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 30,
                'met_value' => 6.0,
                'icon' => '💪',
                'display_order' => 8,
                'description' => 'Strength training with weights',
                'is_active' => true,
            ],
            [
                'name' => 'Tennis / Racquet Sports',
                'slug' => 'tennis',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 35,
                'met_value' => 7.0,
                'icon' => '🎾',
                'display_order' => 9,
                'description' => 'Singles tennis or racquetball',
                'is_active' => true,
            ],
            [
                'name' => 'Soccer / Football',
                'slug' => 'soccer',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 35,
                'met_value' => 7.0,
                'icon' => '⚽',
                'display_order' => 10,
                'description' => 'Playing soccer or football',
                'is_active' => true,
            ],
            [
                'name' => 'Basketball',
                'slug' => 'basketball',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 30,
                'met_value' => 6.0,
                'icon' => '🏀',
                'display_order' => 11,
                'description' => 'Playing basketball (game or practice)',
                'is_active' => true,
            ],
            [
                'name' => 'Aerobics / Dance',
                'slug' => 'aerobics',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 30,
                'met_value' => 6.0,
                'icon' => '💃',
                'display_order' => 12,
                'description' => 'High-impact aerobics or dance fitness',
                'is_active' => true,
            ],
            [
                'name' => 'Rowing',
                'slug' => 'rowing',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 30,
                'met_value' => 6.0,
                'icon' => '🚣',
                'display_order' => 13,
                'description' => 'Rowing machine or water rowing',
                'is_active' => true,
            ],
            [
                'name' => 'Martial Arts',
                'slug' => 'martial-arts',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 35,
                'met_value' => 7.0,
                'icon' => '🥋',
                'display_order' => 14,
                'description' => 'Karate, judo, taekwondo, boxing',
                'is_active' => true,
            ],
            [
                'name' => 'Hiking',
                'slug' => 'hiking',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 25,
                'met_value' => 5.0,
                'icon' => '🥾',
                'display_order' => 15,
                'description' => 'Hiking uphill or on trails',
                'is_active' => true,
            ],
            
            // Light to Moderate (MET 2.5-4.5)
            [
                'name' => 'Yoga',
                'slug' => 'yoga',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 20,
                'met_value' => 4.0,
                'icon' => '🧘',
                'display_order' => 16,
                'description' => 'Hatha or vinyasa yoga practice',
                'is_active' => true,
            ],
            [
                'name' => 'Pilates',
                'slug' => 'pilates',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 15,
                'met_value' => 3.0,
                'icon' => '🤸',
                'display_order' => 17,
                'description' => 'Pilates mat or reformer exercises',
                'is_active' => true,
            ],
            [
                'name' => 'Walking (Brisk)',
                'slug' => 'walking-brisk',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 15,
                'met_value' => 3.5,
                'icon' => '🚶‍♂️',
                'display_order' => 18,
                'description' => 'Walking at 3-4 mph',
                'is_active' => true,
            ],
            [
                'name' => 'Swimming (Light)',
                'slug' => 'swimming-light',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 20,
                'met_value' => 4.5,
                'icon' => '🏊‍♀️',
                'display_order' => 19,
                'description' => 'Leisure swimming or water aerobics',
                'is_active' => true,
            ],
            [
                'name' => 'Stretching / Flexibility',
                'slug' => 'stretching',
                'category' => ActivityCategory::WORKOUT->value,
                'base_points' => 10,
                'met_value' => 2.5,
                'icon' => '🤸‍♀️',
                'display_order' => 20,
                'description' => 'Static or dynamic stretching routine',
                'is_active' => true,
            ],
            
            // ===== NUTRITION ACTIVITIES =====
            [
                'name' => 'Healthy Breakfast',
                'slug' => 'healthy-breakfast',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 20,
                'met_value' => null,
                'icon' => '🍳',
                'display_order' => 30,
                'description' => 'Balanced breakfast with protein, whole grains, and fruits',
                'is_active' => true,
            ],
            [
                'name' => 'Healthy Lunch',
                'slug' => 'healthy-lunch',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 20,
                'met_value' => null,
                'icon' => '🥗',
                'display_order' => 31,
                'description' => 'Nutritious lunch with vegetables and lean protein',
                'is_active' => true,
            ],
            [
                'name' => 'Healthy Dinner',
                'slug' => 'healthy-dinner',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 20,
                'met_value' => null,
                'icon' => '🍽️',
                'display_order' => 32,
                'description' => 'Balanced dinner with vegetables and quality nutrients',
                'is_active' => true,
            ],
            [
                'name' => 'Meal Prep',
                'slug' => 'meal-prep',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 25,
                'met_value' => null,
                'icon' => '🥘',
                'display_order' => 33,
                'description' => 'Preparing healthy meals in advance',
                'is_active' => true,
            ],
            [
                'name' => 'Fruits & Vegetables (5+ servings)',
                'slug' => 'fruits-vegetables',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 15,
                'met_value' => null,
                'icon' => '🍎',
                'display_order' => 34,
                'description' => 'Eating 5 or more servings of fruits and vegetables',
                'is_active' => true,
            ],
            [
                'name' => 'Protein Intake Goal',
                'slug' => 'protein-goal',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 15,
                'met_value' => null,
                'icon' => '🥩',
                'display_order' => 35,
                'description' => 'Meeting daily protein requirements',
                'is_active' => true,
            ],
            [
                'name' => 'Hydration (8+ glasses)',
                'slug' => 'hydration',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 15,
                'met_value' => null,
                'icon' => '💧',
                'display_order' => 36,
                'description' => 'Drinking 8 or more glasses of water',
                'is_active' => true,
            ],
            [
                'name' => 'No Junk Food',
                'slug' => 'no-junk-food',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 20,
                'met_value' => null,
                'icon' => '🚫',
                'display_order' => 37,
                'description' => 'Avoiding processed and junk foods',
                'is_active' => true,
            ],
            [
                'name' => 'Vitamins / Supplements',
                'slug' => 'supplements',
                'category' => ActivityCategory::NUTRITION->value,
                'base_points' => 10,
                'met_value' => null,
                'icon' => '💊',
                'display_order' => 38,
                'description' => 'Taking daily vitamins or supplements',
                'is_active' => true,
            ],
            
            // ===== WELLNESS ACTIVITIES =====
            [
                'name' => 'Quality Sleep (7-9 hours)',
                'slug' => 'quality-sleep',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 30,
                'met_value' => null,
                'icon' => '😴',
                'display_order' => 40,
                'description' => 'Getting 7-9 hours of quality sleep',
                'is_active' => true,
            ],
            [
                'name' => 'Early Morning Wake Up',
                'slug' => 'early-wake',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 15,
                'met_value' => null,
                'icon' => '🌅',
                'display_order' => 41,
                'description' => 'Waking up before 7 AM',
                'is_active' => true,
            ],
            [
                'name' => 'No Screen Before Bed',
                'slug' => 'no-screen-bed',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 15,
                'met_value' => null,
                'icon' => '📵',
                'display_order' => 42,
                'description' => 'Avoiding screens 1 hour before bedtime',
                'is_active' => true,
            ],
            [
                'name' => 'Sunlight Exposure',
                'slug' => 'sunlight',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 15,
                'met_value' => null,
                'icon' => '☀️',
                'display_order' => 43,
                'description' => 'Getting 15-30 minutes of natural sunlight',
                'is_active' => true,
            ],
            [
                'name' => 'Nature / Outdoor Time',
                'slug' => 'nature-time',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 20,
                'met_value' => null,
                'icon' => '🌳',
                'display_order' => 44,
                'description' => 'Spending time outdoors in nature',
                'is_active' => true,
            ],
            [
                'name' => 'Cold Shower',
                'slug' => 'cold-shower',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 20,
                'met_value' => null,
                'icon' => '🚿',
                'display_order' => 45,
                'description' => 'Taking a cold shower for recovery',
                'is_active' => true,
            ],
            [
                'name' => 'Sauna / Steam Room',
                'slug' => 'sauna',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 15,
                'met_value' => null,
                'icon' => '🧖',
                'display_order' => 46,
                'description' => 'Sauna or steam room session',
                'is_active' => true,
            ],
            [
                'name' => 'Social Connection',
                'slug' => 'social-connection',
                'category' => ActivityCategory::WELLNESS->value,
                'base_points' => 15,
                'met_value' => null,
                'icon' => '👥',
                'display_order' => 47,
                'description' => 'Quality time with friends or family',
                'is_active' => true,
            ],
            
            // ===== MINDFULNESS ACTIVITIES =====
            [
                'name' => 'Meditation',
                'slug' => 'meditation',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 25,
                'met_value' => null,
                'icon' => '🧘‍♀️',
                'display_order' => 50,
                'description' => 'Mindfulness or meditation practice (10+ min)',
                'is_active' => true,
            ],
            [
                'name' => 'Breathing Exercises',
                'slug' => 'breathing',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 15,
                'met_value' => null,
                'icon' => '💨',
                'display_order' => 51,
                'description' => 'Deep breathing or pranayama exercises',
                'is_active' => true,
            ],
            [
                'name' => 'Journaling',
                'slug' => 'journaling',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 20,
                'met_value' => null,
                'icon' => '📝',
                'display_order' => 52,
                'description' => 'Daily journaling or gratitude practice',
                'is_active' => true,
            ],
            [
                'name' => 'Reading (Self-Development)',
                'slug' => 'reading',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 20,
                'met_value' => null,
                'icon' => '📚',
                'display_order' => 53,
                'description' => 'Reading for personal growth and learning',
                'is_active' => true,
            ],
            [
                'name' => 'Prayer / Spiritual Practice',
                'slug' => 'prayer',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 20,
                'met_value' => null,
                'icon' => '🙏',
                'display_order' => 54,
                'description' => 'Prayer or spiritual practice',
                'is_active' => true,
            ],
            [
                'name' => 'No Social Media',
                'slug' => 'no-social-media',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 25,
                'met_value' => null,
                'icon' => '📵',
                'display_order' => 55,
                'description' => 'Digital detox - no social media for the day',
                'is_active' => true,
            ],
            [
                'name' => 'Learning / Skill Development',
                'slug' => 'learning',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 20,
                'met_value' => null,
                'icon' => '🎓',
                'display_order' => 56,
                'description' => 'Dedicated time for learning new skills',
                'is_active' => true,
            ],
            [
                'name' => 'Creative Activity',
                'slug' => 'creative',
                'category' => ActivityCategory::MINDFULNESS->value,
                'base_points' => 15,
                'met_value' => null,
                'icon' => '🎨',
                'display_order' => 57,
                'description' => 'Engaging in creative activities (art, music, writing)',
                'is_active' => true,
            ],
        ];

        foreach ($activityTypes as $activityType) {
            ActivityType::firstOrCreate(
                ['slug' => $activityType['slug']],
                $activityType
            );
        }

        $this->command->info('Created ' . count($activityTypes) . ' activity types across 4 categories');
        $this->command->info('Categories: Workout, Nutrition, Wellness, Mindfulness');
    }
}
